services:

    php:
        working_dir: /app
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "80:80"
        volumes:
            - .:/app
